variable "google_project_id" {}
variable "google_default_region" {}
variable "google_default_zone" {}
variable "google_iot_registry_id" {}
variable "google_iot_device_id" {}
variable "google_bigquery_default_region" {}
variable "google_dataflow_default_bucket" {}
variable "stream_processing_window_size" {}
variable "stream_processing_window_frequency" {}
variable "google_bigquery_dataset_id" {}
variable "google_bigquery_metrics_table_id" {}
variable "google_bigquery_inference_table_id" {}
variable "google_bigquery_unknown_message_table_id" {}